package CREATE_DATA;


import java.util.ArrayList;

import model_DAO.DAO_Account;
import model_beans.Account;
import model_utility.EncryptPassword;

public class CreateAccount {

	public static int rdINT(int start, int end) {
		return (int) ((Math.random() * (end - start)) + start);
	}

	public static int rdItem(int arrSize) {
		return (int) ((Math.random() * arrSize));
	}

	public static String ho() {
		ArrayList<String> ho = new ArrayList<String>();
		ho.add("Trần");
		ho.add("Lê");
		ho.add("Trịnh");
		ho.add("Nguyễn");
		ho.add("Châu");
		ho.add("Bùi");
		ho.add("Lâm");
		ho.add("Phan");
		ho.add("Phạm");
		ho.add("Vũ");
		ho.add("Võ");
		ho.add("Dương");
		ho.add("Đỗ");
		ho.add("Ngô");
		ho.add("Hồ");
		ho.add("Đặng");
		ho.add("Huỳnh");
		ho.add("Thạch");
		ho.add("Trương");
		ho.add("Lý");
		return ho.get(rdItem(ho.size()));
	}

	public static String tenDem() {
		ArrayList<String> tenDem = new ArrayList<String>();
		tenDem.add("Văn");
		tenDem.add("Thị");
		tenDem.add("Thanh");
		tenDem.add("Huệ");
		tenDem.add("Hồng");
		tenDem.add("Công");
		tenDem.add("Phước");
		tenDem.add("Gia");
		tenDem.add("Kim");
		tenDem.add("Vân");
		tenDem.add("Mỹ");
		tenDem.add("Tiểu");
		tenDem.add("Minh");
		tenDem.add("Ngọc");
		return tenDem.get(rdItem(tenDem.size()));
	}

	public static String ten() {
		ArrayList<String> ten = new ArrayList<String>();
		ten.add("Bảo");
		ten.add("Đăng");
		ten.add("Cường");
		ten.add("Danh");
		ten.add("Điền");
		ten.add("Anh");
		ten.add("Dung");
		ten.add("Duy");
		ten.add("Hoàng");
		ten.add("Đạt");
		ten.add("Vương");
		ten.add("Hoa");
		ten.add("Yến");
		ten.add("Tâm");
		ten.add("Phụng");
		ten.add("Thu");
		ten.add("Thảo");
		ten.add("Hằng");
		ten.add("Linh");
		ten.add("Hải");
		ten.add("Vinh");
		ten.add("Bằng");
		ten.add("Bình");
		return ten.get(rdItem(ten.size()));
	}

	public static String huyen_tinh() {
		ArrayList<String> huyen_tinh = new ArrayList<String>();
		huyen_tinh.add(" huyện An Biên, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện An Dương, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện An Khê, tỉnh Gia Lai");
		huyen_tinh.add(" huyện An Lão, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện An Lão, tỉnh Bình Định");
		huyen_tinh.add(" huyện An Minh, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện An Nhơn, tỉnh Bình Định");
		huyen_tinh.add(" huyện An Phú, tỉnh An Giang");
		huyen_tinh.add(" huyện Anh Sơn, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Ayun Pa, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Ân Thi, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Ba Bể, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Ba Chẽ, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Ba Đình, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Ba Đồn, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Ba Tơ, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Ba Tri, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Ba Vì, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Bà Rịa, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Bá Thước, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Bác Ái, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Bạc Liêu, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Bạch Long Vĩ, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Bạch Thông, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Bảo Lạc, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Bảo Lâm, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Bảo Lâm, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Bảo Lộc, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Bảo Thắng, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Bảo Yên, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Bát Xát, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Bàu Bàng, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Bắc Bình, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Bắc Giang, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Bắc Hà, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Bắc Kạn, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Bắc Mê, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Bắc Ninh, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Bắc Quang, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Bắc Sơn, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Bắc Tân Uyên, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Bắc Trà My, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Bắc Từ Liêm, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Bắc Yên, tỉnh Sơn La");
		huyen_tinh.add(" huyện Bến Cát, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Bến Cầu, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Bến Lức, tỉnh Long An");
		huyen_tinh.add(" huyện Bến Tre, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Biên Hòa, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Bỉm Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Bình Chánh, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Bình Đại, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Bình Gia, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Bình Giang, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Bình Liêu, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Bình Long, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Bình Lục, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Bình Minh, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Bình Sơn, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Bình Tân, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Bình Tân, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Bình Thạnh, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Bình Thủy, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Bình Xuyên, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Bố Trạch, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Bù Đăng, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Bù Đốp, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Bù Gia Mập, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Buôn Đôn, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Buôn Hồ, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Buôn Ma Thuột, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Cà Mau, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Cai Lậy, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Cai Lậy, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Cái Bè, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Cái Nước, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Cái Răng, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Cam Lâm, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Cam Lộ, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Cam Ranh, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Can Lộc, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Càng Long, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Cao Bằng, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Cao Lãnh, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Cao Lãnh, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Cao Lộc, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Cao Phong, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Cát Hải, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Cát Tiên, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Cẩm Giàng, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Cẩm Khê, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Cẩm Lệ, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Cẩm Mỹ, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Cẩm Phả, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Cẩm Thủy, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Cẩm Xuyên, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Cần Đước, tỉnh Long An");
		huyen_tinh.add(" huyện Cần Giờ, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Cần Giuộc, tỉnh Long An");
		huyen_tinh.add(" huyện Cầu Giấy, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Cầu Kè, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Cầu Ngang, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Châu Đốc, tỉnh An Giang");
		huyen_tinh.add(" huyện Châu Đức, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Châu Phú, tỉnh An Giang");
		huyen_tinh.add(" huyện Châu Thành, tỉnh An Giang");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Long An");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Châu Thành, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Châu Thành A, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Chi Lăng, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Chí Linh, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Chiêm Hóa, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Chợ Đồn, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Chợ Gạo, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Chợ Lách, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Chợ Mới, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Chợ Mới, tỉnh An Giang");
		huyen_tinh.add(" huyện Chơn Thành, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Chư Păh, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Chư Prông, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Chư Pưh, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Chư Sê, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Chương Mỹ, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Con Cuông, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Cô Tô, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Côn Đảo, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Cồn Cỏ, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Cờ Đỏ, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Cù Lao Dung, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Củ Chi, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Cư Kuin, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Cư Jút, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Cư M'gar, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Cửa Lò, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Dầu Tiếng, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Di Linh, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Dĩ An, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Diên Khánh, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Diễn Châu, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Duy Tiên, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Duy Xuyên, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Duyên Hải, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Duyên Hải, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Dương Kinh, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Dương Minh Châu, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Đa Krông, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Đà Bắc, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Đà Lạt, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Đạ Huoai, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Đạ Tẻh, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Đại Lộc, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Đại Từ, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Đắk Đoa, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Đak Pơ, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Đan Phượng, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Đắk Glei, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Đắk Glong, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Đắk Hà, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Đắk Mil, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Đắk R'lấp, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Đắk Song, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Đắk Tô, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Đầm Dơi, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Đầm Hà, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Đam Rông, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Đất Đỏ, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Điện Bàn, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Điện Biên, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Điện Biên Đông, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Điện Biên Phủ, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Đình Lập, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Định Hóa, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Định Quán, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Đoan Hùng, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Đô Lương, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Đồ Sơn, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Đông Anh, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Đông Giang, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Đông Hà, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Đông Hải, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Đông Hòa, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Đông Hưng, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Đông Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Đông Triều, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Đồng Hới, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Đồng Hỷ, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Đồng Phú, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Đồng Văn, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Đồng Xoài, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Đồng Xuân, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Đống Đa, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Đơn Dương, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Đức Cơ, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Đức Hòa, tỉnh Long An");
		huyen_tinh.add(" huyện Đức Huệ, tỉnh Long An");
		huyen_tinh.add(" huyện Đức Linh, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Đức Phổ, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Đức Thọ, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Đức Trọng, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Ea H'leo, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Ea Kar, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Ea Súp, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Gia Bình, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Gia Lâm, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Gia Lộc, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Gia Nghĩa, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Gia Viễn, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Giá Rai, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Giang Thành, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Giao Thủy, tỉnh Nam Định");
		huyen_tinh.add(" huyện Gio Linh, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Giồng Riềng, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Giồng Trôm, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Gò Công, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Gò Công Đông, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Gò Công Tây, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Gò Dầu, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Gò Quao, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Gò Vấp, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Hà Đông, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Hà Giang, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Hà Quảng, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Hà Tiên, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Hà Tĩnh, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Hà Trung, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Hạ Hòa, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Hạ Lang, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Hạ Long, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Hai Bà Trưng, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Hải An, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Hải Châu, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Hải Dương, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Hải Hà, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Hải Hậu, tỉnh Nam Định");
		huyen_tinh.add(" huyện Hải Lăng, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Hàm Tân, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Hàm Thuận Bắc, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Hàm Thuận Nam, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Hàm Yên, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Hậu Lộc, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Hiệp Đức, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Hiệp Hòa, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Hoa Lư, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Hòa An, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Hoà Bình, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Hoà Bình, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Hòa Thành, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Hòa Vang, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Hoài Ân, tỉnh Bình Định");
		huyen_tinh.add(" huyện Hoài Đức, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Hoài Nhơn, tỉnh Bình Định");
		huyen_tinh.add(" huyện Hoàn Kiếm, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Hoàng Mai, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Hoàng Mai, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Hoàng Sa, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Hoàng Su Phì, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Hoằng Hóa, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Hóc Môn, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Hòn Đất, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Hớn Quản, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Hội An, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Hồng Bàng, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Hồng Dân, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Hồng Lĩnh, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Hồng Ngự, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Hồng Ngự, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Huế, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Hưng Hà, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Hưng Nguyên, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Hưng Yên, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Hương Khê, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Hương Sơn, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Hương Thủy, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Hương Trà, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Hướng Hóa, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Hữu Lũng, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Ia Grai, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Ia H'Drai, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Ia Pa, tỉnh Gia Lai");
		huyen_tinh.add(" huyện K'Bang, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Kế Sách, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Khánh Sơn, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Khánh Vĩnh, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Khoái Châu, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Kiên Hải, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Kiên Lương, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Kiến An, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Kiến Thụy, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Kiến Xương, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Kiến Tường, tỉnh Long An");
		huyen_tinh.add(" huyện Kim Bảng, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Kim Bôi, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Kim Động, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Kim Sơn, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Kim Thành, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Kinh Môn, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Kon Plông, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Kon Rẫy, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Kon Tum, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Kông Chro, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Krông Ana, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Krông Bông, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Krông Búk, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Krông Năng, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Krông Nô, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Krông Pa, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Krông Pắk, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Kỳ Anh, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Kỳ Anh, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Kỳ Sơn, tỉnh Nghệ An");
		huyen_tinh.add(" huyện La Gi, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Lạc Dương, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Lạc Sơn, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Lạc Thủy, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Lai Châu, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Lai Vung, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Lang Chánh, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Lạng Giang, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Lạng Sơn, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Lào Cai, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Lắk, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Lâm Bình, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Lâm Hà, tỉnh Lâm Đồng");
		huyen_tinh.add(" huyện Lâm Thao, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Lấp Vò, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Lập Thạch, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Lê Chân, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Lệ Thủy, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Liên Chiểu, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Long Biên, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Long Điền, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Long Hồ, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Long Khánh, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Long Mỹ, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Long Mỹ, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Long Phú, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Long Thành, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Long Xuyên, tỉnh An Giang");
		huyen_tinh.add(" huyện Lộc Bình, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Lộc Hà, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Lộc Ninh, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Lục Nam, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Lục Ngạn, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Lục Yên, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Lương Sơn, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Lương Tài, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Lý Nhân, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Lý Sơn, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Mai Châu, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Mai Sơn, tỉnh Sơn La");
		huyen_tinh.add(" huyện Mang Thít, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Mang Yang, tỉnh Gia Lai");
		huyen_tinh.add(" huyện M'Đrăk, tỉnh Đắk Lắk");
		huyen_tinh.add(" huyện Mèo Vạc, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Mê Linh, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Minh Hóa, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Minh Long, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Mỏ Cày Bắc, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Mỏ Cày Nam, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Móng Cái, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Mộ Đức, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Mộc Châu, tỉnh Sơn La");
		huyen_tinh.add(" huyện Mộc Hóa, tỉnh Long An");
		huyen_tinh.add(" huyện Mù Cang Chải, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Mường Ảng, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Mường Chà, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Mường Khương, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Mường La, tỉnh Sơn La");
		huyen_tinh.add(" huyện Mường Lát, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Mường Lay, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Mường Nhé, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Mường Tè, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Mỹ Đức, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Mỹ Hào, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Mỹ Lộc, tỉnh Nam Định");
		huyen_tinh.add(" huyện Mỹ Tho, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Mỹ Tú, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Mỹ Xuyên, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Na Hang, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Na Rì, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Nam Đàn, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Nam Định, tỉnh Nam Định");
		huyen_tinh.add(" huyện Nam Đông, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Nam Giang, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Nam Sách, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Nam Trà My, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Nam Trực, tỉnh Nam Định");
		huyen_tinh.add(" huyện Nam Từ Liêm, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Năm Căn, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Nậm Pồ, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Nậm Nhùn, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Nga Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Ngã Bảy, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Ngã Năm, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Ngân Sơn, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Nghi Lộc, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Nghi Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Nghi Xuân, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Nghĩa Đàn, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Nghĩa Hành, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Nghĩa Hưng, tỉnh Nam Định");
		huyen_tinh.add(" huyện Nghĩa Lộ, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Ngọc Hiển, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Ngọc Hồi, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Ngọc Lặc, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Ngô Quyền, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Ngũ Hành Sơn, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Nguyên Bình, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Nha Trang, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Nhà Bè, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Nho Quan, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Nhơn Trạch, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Như Thanh, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Như Xuân, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Ninh Bình, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Ninh Giang, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Ninh Hải, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Ninh Hòa, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Ninh Kiều, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Ninh Phước, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Ninh Sơn, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Nông Cống, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Nông Sơn, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Núi Thành, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Ô Môn, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Pác Nặm, tỉnh Bắc Kạn");
		huyen_tinh.add(" huyện Phan Rang-Tháp Chàm, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Phan Thiết, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Phong Điền, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Phong Điền, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Phong Thổ, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Phổ Yên, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Phú Bình, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Phú Giáo, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Phú Hòa, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Phú Lộc, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Phú Lương, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Phú Mỹ, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Phú Nhuận, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Phú Ninh, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Phú Quý, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Phú Quốc, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Phú Riềng, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Phú Tân, tỉnh An Giang");
		huyen_tinh.add(" huyện Phú Tân, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Phú Thiện, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Phú Thọ, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Phú Vang, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Phú Xuyên, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Phù Cát, tỉnh Bình Định");
		huyen_tinh.add(" huyện Phù Cừ, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Phù Mỹ, tỉnh Bình Định");
		huyen_tinh.add(" huyện Phù Ninh, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Phù Yên, tỉnh Sơn La");
		huyen_tinh.add(" huyện Phủ Lý, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Phúc Thọ, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Phúc Yên, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Phụng Hiệp, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Phước Long, tỉnh Bình Phước");
		huyen_tinh.add(" huyện Phước Long, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Phước Sơn, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Pleiku, tỉnh Gia Lai");
		huyen_tinh.add(" huyện Quan Hóa, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Quan Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Quản Bạ, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Quang Bình, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Quảng Điền, tỉnh Thừa Thiên-Huế");
		huyen_tinh.add(" huyện Quảng Hòa, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Quảng Ngãi, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Quảng Ninh, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Quảng Trạch, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Quảng Trị, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Quảng Yên, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Quảng Xương, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Quận 1, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 2, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 3, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 4, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 5, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 6, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 7, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 8, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 9, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 10, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 11, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quận 12, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Quế Phong, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Quế Sơn, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Quế Võ, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Quy Nhơn, tỉnh Bình Định");
		huyen_tinh.add(" huyện Quốc Oai, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Quỳ Châu, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Quỳ Hợp, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Quỳnh Lưu, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Quỳnh Nhai, tỉnh Sơn La");
		huyen_tinh.add(" huyện Quỳnh Phụ, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Rạch Giá, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Sa Đéc, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Sa Pa, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Sa Thầy, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Sầm Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Si Ma Cai, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Sìn Hồ, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Sóc Sơn, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Sóc Trăng, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Sông Cầu, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Sông Công, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Sông Hinh, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Sông Lô, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Sông Mã, tỉnh Sơn La");
		huyen_tinh.add(" huyện Sốp Cộp, tỉnh Sơn La");
		huyen_tinh.add(" huyện Sơn Động, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Sơn Dương, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Sơn Hà, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Sơn Hòa, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Sơn La, tỉnh Sơn La");
		huyen_tinh.add(" huyện Sơn Tây, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Sơn Tây, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Sơn Tịnh, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Sơn Trà, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Tam Bình, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Tam Dương, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Tam Đảo, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Tam Điệp, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Tam Đường, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Tam Kỳ, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Tam Nông, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Tam Nông, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Tánh Linh, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Tân An, tỉnh Long An");
		huyen_tinh.add(" huyện Tân Biên, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Tân Bình, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Tân Châu, tỉnh An Giang");
		huyen_tinh.add(" huyện Tân Châu, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Tân Hiệp, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Tân Hồng, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Tân Hưng, tỉnh Long An");
		huyen_tinh.add(" huyện Tân Kỳ, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Tân Lạc, tỉnh Hòa Bình");
		huyen_tinh.add(" huyện Tân Phú, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Tân Phú, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Tân Phú Đông, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Tân Phước, tỉnh Tiền Giang");
		huyen_tinh.add(" huyện Tân Sơn, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Tân Thạnh, tỉnh Long An");
		huyen_tinh.add(" huyện Tân Trụ, tỉnh Long An");
		huyen_tinh.add(" huyện Tân Uyên, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Tân Uyên, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Tân Yên, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Tây Giang, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Tây Hòa, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Tây Hồ, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Tây Ninh, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Tây Sơn, tỉnh Bình Định");
		huyen_tinh.add(" huyện Thạch An, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Thạch Hà, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Thạch Thành, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Thạch Thất, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Thái Bình, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Thái Hòa, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Thái Nguyên, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Thái Thụy, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Than Uyên, tỉnh Lai Châu");
		huyen_tinh.add(" huyện Thanh Ba, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Thanh Bình, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Thanh Chương, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Thanh Hà, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Thanh Hóa, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Thanh Khê, tỉnh Đà Nẵng");
		huyen_tinh.add(" huyện Thanh Liêm, tỉnh Hà Nam");
		huyen_tinh.add(" huyện Thanh Miện, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Thanh Oai, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Thanh Sơn, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Thanh Thủy, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Thanh Trì, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Thanh Xuân, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Thạnh Hóa, tỉnh Long An");
		huyen_tinh.add(" huyện Thạnh Phú, tỉnh Bến Tre");
		huyen_tinh.add(" huyện Thạnh Trị, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Tháp Mười, tỉnh Đồng Tháp");
		huyen_tinh.add(" huyện Thăng Bình, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Thiệu Hóa, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Thọ Xuân, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Thoại Sơn, tỉnh An Giang");
		huyen_tinh.add(" huyện Thống Nhất, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Thốt Nốt, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Thới Bình, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Thới Lai, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Thủ Dầu Một, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Thủ Đức, tỉnh TP Hồ Chí Minh");
		huyen_tinh.add(" huyện Thủ Thừa, tỉnh Long An");
		huyen_tinh.add(" huyện Thuận An, tỉnh Bình Dương");
		huyen_tinh.add(" huyện Thuận Bắc, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Thuận Châu, tỉnh Sơn La");
		huyen_tinh.add(" huyện Thuận Nam, tỉnh Ninh Thuận");
		huyen_tinh.add(" huyện Thuận Thành, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Thủy Nguyên, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Thường Tín, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Thường Xuân, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Tiên Du, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Tiền Hải, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Tiên Lãng, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Tiên Lữ, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Tiên Phước, tỉnh Quảng Nam");
		huyen_tinh.add(" huyện Tiên Yên, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Tiểu Cần, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Tịnh Biên, tỉnh An Giang");
		huyen_tinh.add(" huyện Trà Bồng, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Trà Cú, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Trà Ôn, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Trà Vinh, tỉnh Trà Vinh");
		huyen_tinh.add(" huyện Trạm Tấu, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Tràng Định, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Trảng Bàng, tỉnh Tây Ninh");
		huyen_tinh.add(" huyện Trảng Bom, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Trấn Yên, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Trần Đề, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Trần Văn Thời, tỉnh Cà Mau");
		huyen_tinh.add(" huyện Tri Tôn, tỉnh An Giang");
		huyen_tinh.add(" huyện Triệu Phong, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Triệu Sơn, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Trùng Khánh, tỉnh Cao Bằng");
		huyen_tinh.add(" huyện Trực Ninh, tỉnh Nam Định");
		huyen_tinh.add(" huyện Trường Sa, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Tủa Chùa, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Tuần Giáo, tỉnh Điện Biên");
		huyen_tinh.add(" huyện Tu Mơ Rông, tỉnh Kon Tum");
		huyen_tinh.add(" huyện Tuy An, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Tuy Đức, tỉnh Đăk Nông");
		huyen_tinh.add(" huyện Tuy Hòa, tỉnh Phú Yên");
		huyen_tinh.add(" huyện Tuy Phong, tỉnh Bình Thuận");
		huyen_tinh.add(" huyện Tuy Phước, tỉnh Bình Định");
		huyen_tinh.add(" huyện Tuyên Hóa, tỉnh Quảng Bình");
		huyen_tinh.add(" huyện Tuyên Quang, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Tư Nghĩa, tỉnh Quảng Ngãi");
		huyen_tinh.add(" huyện Tứ Kỳ, tỉnh Hải Dương");
		huyen_tinh.add(" huyện Từ Sơn, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Tương Dương, tỉnh Nghệ An");
		huyen_tinh.add(" huyện U Minh, tỉnh Cà Mau");
		huyen_tinh.add(" huyện U Minh Thượng, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Uông Bí, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Ứng Hòa, tỉnh Hà Nội");
		huyen_tinh.add(" huyện Vạn Ninh, tỉnh Khánh Hòa");
		huyen_tinh.add(" huyện Văn Bàn, tỉnh Lào Cai");
		huyen_tinh.add(" huyện Văn Chấn, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Văn Giang, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Văn Lãng, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Văn Lâm, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Văn Quan, tỉnh Lạng Sơn");
		huyen_tinh.add(" huyện Văn Yên, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Vân Canh, tỉnh Bình Định");
		huyen_tinh.add(" huyện Vân Đồn, tỉnh Quảng Ninh");
		huyen_tinh.add(" huyện Vân Hồ, tỉnh Sơn La");
		huyen_tinh.add(" huyện Vị Thanh, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Vị Thủy, tỉnh Hậu Giang");
		huyen_tinh.add(" huyện Vị Xuyên, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Việt Trì, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Việt Yên, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Vinh, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Vĩnh Bảo, tỉnh Hải Phòng");
		huyen_tinh.add(" huyện Vĩnh Châu, tỉnh Sóc Trăng");
		huyen_tinh.add(" huyện Vĩnh Cửu, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Vĩnh Hưng, tỉnh Long An");
		huyen_tinh.add(" huyện Vĩnh Linh, tỉnh Quảng Trị");
		huyen_tinh.add(" huyện Vĩnh Long, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Vĩnh Lộc, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Vĩnh Lợi, tỉnh Bạc Liêu");
		huyen_tinh.add(" huyện Vĩnh Thạnh, tỉnh Bình Định");
		huyen_tinh.add(" huyện Vĩnh Thạnh, tỉnh Cần Thơ");
		huyen_tinh.add(" huyện Vĩnh Thuận, tỉnh Kiên Giang");
		huyen_tinh.add(" huyện Vĩnh Tường, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Vĩnh Yên, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Võ Nhai, tỉnh Thái Nguyên");
		huyen_tinh.add(" huyện Vũ Quang, tỉnh Hà Tĩnh");
		huyen_tinh.add(" huyện Vũ Thư, tỉnh Thái Bình");
		huyen_tinh.add(" huyện Vụ Bản, tỉnh Nam Định");
		huyen_tinh.add(" huyện Vũng Liêm, tỉnh Vĩnh Long");
		huyen_tinh.add(" huyện Vũng Tàu, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Xín Mần, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Xuân Lộc, tỉnh Đồng Nai");
		huyen_tinh.add(" huyện Xuân Trường, tỉnh Nam Định");
		huyen_tinh.add(" huyện Xuyên Mộc, tỉnh Bà Rịa-Vũng Tàu");
		huyen_tinh.add(" huyện Ý Yên, tỉnh Nam Định");
		huyen_tinh.add(" huyện Yên Bái, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Yên Bình, tỉnh Yên Bái");
		huyen_tinh.add(" huyện Yên Châu, tỉnh Sơn La");
		huyen_tinh.add(" huyện Yên Dũng, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Yên Định, tỉnh Thanh Hóa");
		huyen_tinh.add(" huyện Yên Khánh, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Yên Lạc, tỉnh Vĩnh Phúc");
		huyen_tinh.add(" huyện Yên Lập, tỉnh Phú Thọ");
		huyen_tinh.add(" huyện Yên Minh, tỉnh Hà Giang");
		huyen_tinh.add(" huyện Yên Mô, tỉnh Ninh Bình");
		huyen_tinh.add(" huyện Yên Mỹ, tỉnh Hưng Yên");
		huyen_tinh.add(" huyện Yên Phong, tỉnh Bắc Ninh");
		huyen_tinh.add(" huyện Yên Sơn, tỉnh Tuyên Quang");
		huyen_tinh.add(" huyện Yên Thành, tỉnh Nghệ An");
		huyen_tinh.add(" huyện Yên Thế, tỉnh Bắc Giang");
		huyen_tinh.add(" huyện Yên Thủy, tỉnh Hòa Bình");

		return huyen_tinh.get(rdItem(huyen_tinh.size()));
	}

	public static String xa() {
		ArrayList<String> xa = new ArrayList<String>();
		xa.add(" phường Đa Kao ");
		xa.add(" phường Bến Nghé ");
		xa.add(" phường Bến Thành ");
		xa.add(" phường Nguyễn Thái Bình ");
		xa.add(" phường Phạm Ngũ Lão ");
		xa.add(" phường Cầu Ông Lãnh ");
		xa.add(" phường Cô Giang ");
		xa.add(" phường Nguyễn Cư Trinh ");
		xa.add(" phường Cầu Kho ");
		xa.add(" phường Thạnh Xuân ");
		xa.add(" phường Thạnh Lộc ");
		xa.add(" phường Hiệp Thành ");
		xa.add(" phường Thới An ");
		xa.add(" phường Tân Chánh Hiệp ");
		xa.add(" phường An Phú Đông ");
		xa.add(" phường Tân Thới Hiệp ");
		xa.add(" phường Trung Mỹ Tây ");
		xa.add(" phường Tân Hưng Thuận ");
		xa.add(" phường Đông Hưng Thuận ");
		xa.add(" phường Tân Thới Nhất ");
		xa.add(" phường Linh Xuân ");
		xa.add(" phường Bình Chiểu ");
		xa.add(" phường Linh Trung ");
		xa.add(" phường Tam Bình ");
		xa.add(" phường Tam Phú ");
		xa.add(" phường Hiệp Bình Phước ");
		xa.add(" phường Hiệp Bình Chánh ");
		xa.add(" phường Linh Chiểu ");
		xa.add(" phường Linh Tây ");
		xa.add(" phường Linh Đông ");
		xa.add(" phường Bình Thọ ");
		xa.add(" phường Trường Thọ ");
		xa.add(" phường Long Bình ");
		xa.add(" phường Long Thạnh Mỹ ");
		xa.add(" phường Tân Phú ");
		xa.add(" phường Hiệp Phú ");
		xa.add(" phường Tăng Nhơn Phú A ");
		xa.add(" phường Tăng Nhơn Phú B ");
		xa.add(" phường Phước Long B ");
		xa.add(" phường Phước Long A ");
		xa.add(" phường Trường Thạnh ");
		xa.add(" phường Long Phước ");
		xa.add(" phường Long Trường ");
		xa.add(" phường Phước Bình ");
		xa.add(" phường Phú Hữu ");
		xa.add(" phường Tân Sơn Nhì ");
		xa.add(" phường Tây Thạnh ");
		xa.add(" phường Sơn Kỳ ");
		xa.add(" phường Tân Qúy ");
		xa.add(" phường Tân Thành ");
		xa.add(" phường Phú Thọ Hoà ");
		xa.add(" phường Phú Thạnh ");
		xa.add(" phường Phú Trung ");
		xa.add(" phường Hoà Thạnh ");
		xa.add(" phường Hiệp Tân ");
		xa.add(" phường Tân Thới Hoà ");
		xa.add(" phường Thảo Điền ");
		xa.add(" phường An Phú ");
		xa.add(" phường Bình An ");
		xa.add(" phường Bình Trưng Đông ");
		xa.add(" phường Bình Trưng Tây ");
		xa.add(" phường Bình Khánh ");
		xa.add(" phường An Khánh ");
		xa.add(" phường Cát Lái ");
		xa.add(" phường Thạnh Mỹ Lợi ");
		xa.add(" phường An Lợi Đông ");
		xa.add(" phường Thủ Thiêm ");
		xa.add(" phường Bình Hưng Hòa ");
		xa.add(" phường Bình Hưng Hoà A ");
		xa.add(" phường Bình Hưng Hoà B ");
		xa.add(" phường Bình Trị Đông ");
		xa.add(" phường Bình Trị Đông A ");
		xa.add(" phường Bình Trị Đông B ");
		xa.add(" phường Tân Tạo ");
		xa.add(" phường Tân Tạo A ");
		xa.add(" phường An Lạc ");
		xa.add(" phường An Lạc A ");
		xa.add(" phường Tân Thuận Đông ");
		xa.add(" phường Tân Thuận Tây ");
		xa.add(" phường Tân Kiểng ");
		xa.add(" phường Tân Hưng ");
		xa.add(" phường Bình Thuận ");
		xa.add(" phường Tân Quy ");
		xa.add(" phường Phú Thuận ");
		xa.add(" phường Tân Phú ");
		xa.add(" phường Tân Phong ");
		xa.add(" phường Phú Mỹ ");
		xa.add(" thị trấn Củ Chi ");
		xa.add(" xã Phú Mỹ Hưng ");
		xa.add(" xã An Phú ");
		xa.add(" xã Trung Lập Thượng ");
		xa.add(" xã An Nhơn Tây ");
		xa.add(" xã Nhuận Đức ");
		xa.add(" xã Phạm Văn Cội ");
		xa.add(" xã Phú Hòa Đông ");
		xa.add(" xã Trung Lập Hạ ");
		xa.add(" xã Trung An ");
		xa.add(" xã Phước Thạnh ");
		xa.add(" xã Phước Hiệp ");
		xa.add(" xã Tân An Hội ");
		xa.add(" xã Phước Vĩnh An ");
		xa.add(" xã Thái Mỹ ");
		xa.add(" xã Tân Thạnh Tây ");
		xa.add(" xã Hòa Phú ");
		xa.add(" xã Tân Thạnh Đông ");
		xa.add(" xã Bình Mỹ ");
		xa.add(" xã Tân Phú Trung ");
		xa.add(" xã Tân Thông Hội ");
		xa.add(" thị trấn Hóc Môn ");
		xa.add(" xã Tân Hiệp ");
		xa.add(" xã Nhị Bình ");
		xa.add(" xã Đông Thạnh ");
		xa.add(" xã Tân Thới Nhì ");
		xa.add(" xã Thới Tam Thôn ");
		xa.add(" xã Xuân Thới Sơn ");
		xa.add(" xã Tân Xuân ");
		xa.add(" xã Xuân Thới Đông ");
		xa.add(" xã Trung Chánh ");
		xa.add(" xã Xuân Thới Thượng ");
		xa.add(" xã Bà Điểm ");
		xa.add(" thị trấn Tân Túc ");
		xa.add(" xã Phạm Văn Hai ");
		xa.add(" xã Vĩnh Lộc A ");
		xa.add(" xã Vĩnh Lộc B ");
		xa.add(" xã Bình Lợi ");
		xa.add(" xã Lê Minh Xuân ");
		xa.add(" xã Tân Nhựt ");
		xa.add(" xã Tân Kiên ");
		xa.add(" xã Bình Hưng ");
		xa.add(" xã Phong Phú ");
		xa.add(" xã An Phú Tây ");
		xa.add(" xã Hưng Long ");
		xa.add(" xã Đa Phước ");
		xa.add(" xã Tân Quý Tây ");
		xa.add(" xã Bình Chánh ");
		xa.add(" xã Quy Đức ");
		xa.add(" thị trấn Nhà Bè ");
		xa.add(" xã Phước Kiển ");
		xa.add(" xã Phước Lộc ");
		xa.add(" xã Nhơn Đức ");
		xa.add(" xã Phú Xuân ");
		xa.add(" xã Long Thới ");
		xa.add(" xã Hiệp Phước ");
		xa.add(" thị trấn Cần Thạnh ");
		xa.add(" xã Bình Khánh ");
		xa.add(" xã Tam Thôn Hiệp ");
		xa.add(" xã An Thới Đông ");
		xa.add(" xã Thạnh An ");
		xa.add(" xã Long Hòa ");
		xa.add(" xã Lý Nhơn ");
		return xa.get(rdItem(xa.size()));
	}

	public static String duong() {
		ArrayList<String> duong = new ArrayList<String>();
		duong.add(" đường Bành Văn Trân");
		duong.add(" đường Bế Văn Cắm");
		duong.add(" đường Bế Văn Đàn");
		duong.add(" đường Bế Văn Thành");
		duong.add(" đường Bùi Đình Cư");
		duong.add(" đường Bùi Ngọc Dương");
		duong.add(" đường Bùi Quang Thận");
		duong.add(" đường Cao Lương Bằng");
		duong.add(" đường Châu Văn Mẫn");
		duong.add(" đường Chu Cẩm Phong");
		duong.add(" đường Chu Văn Khâm");
		duong.add(" đường Chu Văn Mùi");
		duong.add(" đường Cù Chính Lan");
		duong.add(" đường Dương Đức Thùng");
		duong.add(" đường Dương Minh Châu");
		duong.add(" đường Dương Quảng Châu");
		duong.add(" đường Dương Văn Nội");
		duong.add(" đường Đàm Văn Ngụy");
		duong.add(" đường Đặng Đình Hồ");
		duong.add(" đường Đặng Đức Song");
		duong.add(" đường Đặng Quang Cầm");
		duong.add(" đường Đặng Thùy Trâm");
		duong.add(" đường Đặng Trần Đức");
		duong.add(" đường Điểu Cải");
		duong.add(" đường Đinh Núp");
		duong.add(" đường Đinh Thị Vân");
		duong.add(" đường Đinh Văn Mẫu");
		duong.add(" đường Đoàn Sinh Hưởng");
		duong.add(" đường Đoàn Văn Thắng");
		duong.add(" đường Đồng Đen");
		duong.add(" đường Đỗ Kim Tuyến");
		duong.add(" đường Đỗ Thế Chấp");
		duong.add(" đường Đỗ Xuân Hợp");
		duong.add(" đường Giáp Văn Cương");
		duong.add(" đường Hà Minh Trí");
		duong.add(" đường Hà Văn Chúc");
		duong.add(" đường Hà Văn Noa");
		duong.add(" đường Hoàng Lê Kha");
		duong.add(" đường Hoàng Kim Giao");
		duong.add(" đường Hoàng Khắc Dược");
		duong.add(" đường Hoàng Minh Đạo");
		duong.add(" đường Hoàng Ngân");
		duong.add(" đường Hoàng Văn Cón");
		duong.add(" đường Hoàng Văn Nghiên");
		duong.add(" đường Hoàng Văn Nô");
		duong.add(" đường Hoàng Văn Thượng");
		duong.add(" đường Hồ Hảo Hớn");
		duong.add(" đường Hồ Kan Lịch");
		duong.add(" đường Hồ Thị Bi");
		duong.add(" đường Hồ Thị Kỷ");
		duong.add(" đường Huỳnh Văn Nghệ");
		duong.add(" đường Kim Đồng");
		duong.add(" đường Kpă KLơng");
		duong.add(" đường La Thị Tám");
		duong.add(" đường La Văn Cầu");
		duong.add(" đường Lâm Viết Hữu");
		duong.add(" đường Lê Bình");
		duong.add(" đường Lê Đình Chinh");
		duong.add(" đường Lê Độ");
		duong.add(" đường Lê Gia Đỉnh");
		duong.add(" đường Lê Hữu Thúy");
		duong.add(" đường Lê Mã Lương");
		duong.add(" đường Lê Tấn Quốc");
		duong.add(" đường Lê Tấn Quốc");
		duong.add(" đường Lê Thanh Đạo");
		duong.add(" đường Lê Thế Trung");
		duong.add(" đường Lê Thị Hồng Gấm");
		duong.add(" đường Lê Thị Riêng");
		duong.add(" đường Lê Văn Dỵ");
		duong.add(" đường Lê Văn Một");
		duong.add(" đường Lê Xuân Tấu");
		duong.add(" đường Lộc Văn Trọng");
		duong.add(" đường Lục Sĩ Thành");
		duong.add(" đường Lương Văn Tụy");
		duong.add(" đường Lưu Viết Thoảng");
		duong.add(" đường Lý Đại Bàng");
		duong.add(" đường Lý Văn Mưu");
		duong.add(" đường Mạc Thị Bưởi");
		duong.add(" đường Mai Năng");
		duong.add(" đường Neáng Nghés");
		duong.add(" đường Ngô Quang Nhã");
		duong.add(" đường Ngô Thất Sơn");
		duong.add(" đường Nguyễn Đức Hùng");
		duong.add(" đường Nguyễn Hữu Trí");
		duong.add(" đường Nguyễn Mạnh Quân");
		duong.add(" đường Nguyễn Ngọc Bảo");
		duong.add(" đường Nguyễn Ngọc Nại");
		duong.add(" đường Nguyễn Quốc Trị");
		duong.add(" đường Nguyễn Tài");
		duong.add(" đường Nguyễn Thị Định");
		duong.add(" đường Nguyễn Thành Trung");
		duong.add(" đường Nguyễn Thái Bình");
		duong.add(" đường Nguyễn Văn Đệ");
		duong.add(" đường Nguyễn Văn Lập");
		duong.add(" đường Nguyễn Hữu Vị");
		duong.add(" đường Nguyễn Văn Thương");
		duong.add(" đường Nguyễn Văn Tre");
		duong.add(" đường Nguyễn Văn Trỗi");
		duong.add(" đường Nguyễn Văn Ty");
		duong.add(" đường Nông Văn Việt");
		duong.add(" đường Phạm Ngọc Thảo");
		duong.add(" đường Phạm Thanh Quyết");
		duong.add(" đường Phạm Tuân");
		duong.add(" đường Phạm Văn Cội");
		duong.add(" đường Phạm Văn Hai");
		duong.add(" đường Phạm Văn Trà");
		duong.add(" đường Phạm Xuân Ẩn");
		duong.add(" đường Phan Đình Giót");
		duong.add(" đường Phan Trung Kiên");
		duong.add(" đường Phan Tư");
		duong.add(" đường Phan Kim Kỳ");
		duong.add(" đường Trần Văn Xuân");
		duong.add(" đường Hoàng Văn Quyết");
		duong.add(" đường Nguyễn Quang Lộc");
		duong.add(" đường Nguyễn Văn Thoa");
		duong.add(" đường Bùi Anh Tuấn");
		duong.add(" đường Nguyễn Ngọc Chiến");
		duong.add(" đường Vũ Danh Tòng");
		duong.add(" đường Nguyễn Văn Toản");
		duong.add(" đường Trần Quang Thắng");
		duong.add(" đường Phùng Quang Thanh");
		duong.add(" đường Phùng Văn Khầu");
		duong.add(" đường Sơn Cang");
		duong.add(" đường Sơn Ton");
		duong.add(" đường Tạ Quốc Luật");
		duong.add(" đường Tạ Thị Kiều");
		duong.add(" đường Tiêu Văn Mẫn");
		duong.add(" đường Tô Vĩnh Diện");
		duong.add(" đường Tống Viết Dương");
		duong.add(" đường Trần Bội Cơ");
		duong.add(" đường Trần Can");
		duong.add(" đường Trần Công An");
		duong.add(" đường Trần Đình Hùng");
		duong.add(" đường Trần Hanh");
		duong.add(" đường Trần Văn Đang");
		duong.add(" đường Trần Văn Kiểu");
		duong.add(" đường Trần Văn Ơn");
		duong.add(" đường Trần Văn Tư");
		duong.add(" đường Tạ Quang Tỷ");
		duong.add(" đường Đỗ Văn Cầm");
		duong.add(" đường (Hoàng Cầm)");
		duong.add(" đường Triệu Xuân Tâng");
		duong.add(" đường Triệu Văn Báo");
		duong.add(" đường Trịnh Trọng Thập");
		duong.add(" đường Trương Đức Hai");
		duong.add(" đường Trương Hữu Dem");
		duong.add(" đường Vũ Văn Hiếu");
		duong.add(" đường Vũ Xuân Thiều");
		duong.add(" đường Hồ Thanh Đình");
		duong.add(" đường Mai Xuân Vĩnh");
		duong.add(" đường Võ Trọng Việt");
		duong.add(" đường Bùi Thanh Hường");
		duong.add(" đường Nguyễn Văn Y");
		duong.add(" đường Nguyễn Xước Hiện");

		return duong.get(rdItem(duong.size()));
	}

	static String rdText(int n) {
		// chose a Character random from this String
		String AlphaNumericString = "0123456789" + "abcdefghijklmnopqrstuvxyz";

		// create StringBuffer size of AlphaNumericString
		StringBuilder sb = new StringBuilder(n);

		for (int i = 0; i < n; i++) {

			// generate a random number between
			// 0 to AlphaNumericString variable length
			int index = (int) (AlphaNumericString.length() * Math.random());

			// add Character one by one in end of sb
			sb.append(AlphaNumericString.charAt(index));
		}

		return sb.toString();
	}

	public static String domain() {
		ArrayList<String> domain = new ArrayList<String>();
		domain.add("gmail.com");
		domain.add("outlook.com.vn");
		domain.add("outlook.com");
		domain.add("hotmail.com");
		domain.add("yahoo.com");
		domain.add("hcmuaf.edu.vn");
		domain.add("edu.vn");
		domain.add("gmail.com");
		domain.add("gmail.com");
		domain.add("gmail.com");
		return domain.get(rdItem(domain.size()));
	}

	public static String soNha() {

		return rdINT(123, 965) + "/" + rdINT(11, 87);
	}

	///// HỌ TÊN ĐẦY ĐỦ
	public static String fullName() {
		return ho() + " " + tenDem() + " " + ten();
	}

///// SỐ ĐIỆN THOẠI
	public static String SDT() {
		return "09" + rdINT(12345678, 98763456);
	}

///// ĐỊA CHỈ ĐẦY ĐỦ
	public static String fullDiaChi() {
		return soNha() + "," + duong() + "," + xa() + "," + huyen_tinh();
	}

	public static String fullEmail() {
		return rdText(10) + "@" + domain();
	}

	public static String ngayTao() {
		return rdINT(2011, 2021) + "-0" + rdINT(1, 9) + "-" + rdINT(10, 28);
	}

	public static String password() {
		return EncryptPassword.md5(rdText(3));
	}

	public static Account acc() {
		return new Account(fullEmail(), password(), "CUSTOMER", "ENABLE", ngayTao(), fullName(), SDT(), fullDiaChi());
	}

	public static void main(String[] args) {

		DAO_Account daoACC = new DAO_Account();	

		for (int i = 0; i < 401; i++) {
			daoACC.add(acc());
		}

	}

}
